#!/usr/bin/env python

#merge two sorted arrays

def mergeSortedArrays(a,b,n,m,result):
    i=0
    j=0
    while(i<n and j<m):
        if(a[i] >= b[j]):
            result.append(a[i])
            i+=1
        else:
            result.append(b[j])
            j+=1 
    if(i<n):
        for p in range(i,n):
            result.append(a[p])
    else:
        for p in range(j,m):
            result.append(b[p])
    return result

tc=input()
for i in range(tc):
     inA,inB=raw_input().split();
     n=int(inA)
     m=int(inB)
     arr1=list(map(int, raw_input().strip().split(" ")))
     arr2=list(map(int, raw_input().strip().split(" ")))
     result=[]
     result=mergeSortedArrays(arr1,arr2,n,m,result)
     for x in result:
        print x,
     print ""
     
